In [1]:
#importing the necessary libraries.
import numpy as np
import pandas as pd

In [2]:
#reading in the data.
data = pd.read_csv("dataexercise2.csv")

In [3]:
# Creating the design matrix.
x=data.drop(columns=["y"])

In [4]:
# Creating the target column vector.
y = data["y"]

In [5]:
# setting the variance for theta (assuming mean zero).
sig_sq = 25 

In [6]:
#Function for calculating the gradient of the log likelihood.
def gradient(theta,x,y,sig_sq):
    P = np.exp(np.dot(x,theta))
    P = P.flatten()
    return (((-1.0/sig_sq)*theta).T + np.dot(x.T,y-P)).T

In [7]:
#Function for calculating the hessian of the log likelihood.
def hessian(theta,x,y,sig_sq):
    P = np.exp(np.dot(x,theta))
    P = P.flatten() # required for the diagonalisation
    return (-(1.0/sig_sq)*np.eye(len(theta)) - np.dot(x.T,np.dot(np.diag(P),x)))

In [8]:
#initializing theta.
theta = np.zeros((4,1))

In [9]:
#Calculating the MAP estimate of theta using Newton's Raphson Method.
for i in range(10):
    theta = theta - np.dot(np.linalg.inv(hessian(theta,x,y,sig_sq)),gradient(theta,x,y,sig_sq))
    

In [10]:
print("The MAP estimate for theta is " + str(theta.flatten()))

The MAP estimate for theta is [ 1.12649475  0.42890301  0.01506197 -0.05408826]


In [11]:
#Calculating the Covariance matrix for the laplace approximation. 
Laplace_Covariance_Matrix = np.linalg.inv(-hessian(theta.flatten(),x,y,sig_sq))

In [12]:
print("The covariance for the Laplace Approximation is \n" +str(Laplace_Covariance_Matrix))

The covariance for the Laplace Approximation is 
[[ 0.0313798  -0.00819078  0.0011658  -0.00139297]
 [-0.00819078  0.00305527 -0.00031135  0.00066121]
 [ 0.0011658  -0.00031135  0.01480116 -0.00146565]
 [-0.00139297  0.00066121 -0.00146565  0.01172734]]
